### PR TITLE
Upgrade mdx/react and fix theming lines in config

### PR DESCRIPTION
**Pull request by OmniTroid**
On running yarn start on current master I get
```[ERROR] Error: Docusaurus could not load module at path ".../docusaurus.config.js"
Cause: Cannot read properties of undefined (reading 'dracula')
```

Which is fixed by updating the theme config lines in docusaurus config.

Also got some import errors from import @mdx/react from dependencies, so upgraded that.

Running `yarn && yarn start` now works from a clean clone (using yarn 1.22.22).

Updated docusaurus version, set yarn as package manager and lock node version using .nvmrc.

Using the readme instructions, it should now work with no assumptions of existing node or yarn installations.

### CODE REVIEW

**Comment by stonedDiscord** [comment]
I ran into the same issues yesterday and believe I fixed them, at least one of the lines in this PR undoes it
Refer to:
https://github.com/FormidableLabs/prism-react-renderer?tab=readme-ov-file#change-theme-imports

**Comment by OmniTroid** [comment]
Right, the current master has prism v2 style imports, but the dependency listed in package.json is
`"prism-react-renderer": "1.2.1",`,
so simply upgrading prism to v2 and reverting the lines should fix it and properly use v2.

**Comment by OmniTroid** [comment]
Upgraded docusaurus and prism and reverted the theme config change now. There are still some warning on yarn install, but it does build and run out of the box.

**Comment by stonedDiscord** [comment]
i was under the impression i already updated docusaurus to 3.4, I must've forgotten to push it

**Pull request merged**
